### ISSUE TITLE
Very interesting Use of py NX

### ISSUE THREAD

**Issue by cyrsis** [lucasvieirasilva/python-poetry-monorepo#1]
I took the step to merge into single Virtual Env with poetry

Then I think by the end of the day, I probably want  make some dockerFile with fastapi for deployment
 
But wasnt really sure the right way to make this work

**Comment by lucasvieirasilva** [comment]
@cyrsis Well, in fact, the idea to have a single virtual env is useful when you have many Python projects that share the same external libraries like we have the standard node.js Nx monorepo, this approach also reduces the amount of time/compute/disk to install all the dependencies for each project individually, especially for development dependencies, that is usually the same for the entire workspace, once you use the nx build command the whl file generated contains the correct external and internal dependencies.

One limitation of this approach is you can't have version conflicts between your monorepo projects, they must use the same or compatible version.

With the `whl` file you can copy to your docker image and use pip to install and initialize your module.

**Comment by cyrsis** [comment]
Sounds Great, then everything is the whl
Yes, Python 3.9, Python 3.8 , Conda and they dont work too well with those machine learning library
If I have the whi , I can build the image faster too

Thanks

**Comment by lucasvieirasilva** [comment]
Yep, you can use pip to install the whl with all the dependencies, if you have any questions let me know!

**Comment by cyrsis** [comment]
Thanks
